- id: errcheck
  name: errcheck
  entry: pre-gommit-hooks errcheck
  types:
    - go
  language: golang
  additional_dependencies:
    - github.com/kisielk/errcheck@v1.9.0
  description: Run errcheck on Go files
- id: goimports
  name: goimports
  entry: goimports -l -w
  types:
    - go
  language: golang
  additional_dependencies:
    - golang.org/x/tools/cmd/goimports@v0.34.1-0.19700101000000-87f68886ec5f
  description: Run goimports on Go files
- id: golangci-lint
  name: golangci-lint
  entry: pre-gommit-hooks golangci-lint
  types:
    - go
  language: golang
  additional_dependencies:
    - github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
  description: Run golangci-lint on Go files
- id: gofumpt
  name: gofumpt
  entry: gofumpt -l -w
  types:
    - go
  language: golang
  additional_dependencies:
    - mvdan.cc/gofumpt@v0.8.0
  description: Run gofumpt on Go files
- id: staticcheck
  name: staticcheck
  entry: pre-gommit-hooks staticcheck
  types:
    - go
  language: golang
  additional_dependencies:
    - honnef.co/go/tools/cmd/staticcheck@v0.6.1
  description: Run staticcheck on Go files
- id: govet
  name: govet
  entry: pre-gommit-hooks govet
  types:
    - go
  language: golang
  additional_dependencies: []
  description: Run go vet on Go files
- id: gofmt
  name: gofmt
  entry: pre-gommit-hooks gofmt
  types:
    - go
  language: golang
  additional_dependencies: []
  description: Run go fmt on Go files
- id: gofix
  name: gofix
  entry: pre-gommit-hooks gofix
  types:
    - go
  language: golang
  additional_dependencies: []
  description: Run go fix on Go files
