name: update

on:
  schedule:
    - cron: "0 4 * * 2,4,6"
  workflow_dispatch:

defaults:
  run:
    shell: nu {0}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: yezz123/setup-uv@v4

      - run: uv pip install --system .
      - run: python pre_gommit_hooks.py
      - uses: pre-commit/action@v3.0.1
        continue-on-error: true

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            hook:
              - '.pre-commit-hooks.yaml'

      - run: |
          let today = date now | format date "v%Y.%m.%d"
          $"TODAY=($today)\n" | save --append $env.GITHUB_OUTPUT
        id: date

      - if: steps.changes.outputs.hook == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatically update pre-commit hooks: ${{ steps.date.outputs.TODAY }}"
          tagging_message: ${{ steps.date.outputs.TODAY }}
