name: update

on:
  schedule:
    - cron: "0 4 * * 2,4,6"
  workflow_dispatch:

defaults:
  run:
    shell: nu {0}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: yezz123/setup-uv@v4

      - run: uv pip install --system .

      - run: python pre_gommit_hooks.py
        id: update

      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{yaml,yml}
          only_changed: true

      - name: Get calver
        run: |
          let today = date now | format date "v%Y.%m.%d"
          print $today
          $"TODAY=($today)\n" | save --append $env.GITHUB_OUTPUT
        id: date

      - name: Update README
        if: steps.update.outputs.UPDATED == 'true'
        run: |
          let today = '${{ steps.date.outputs.TODAY }}'
          open README.md | str replace --regex v\d+\.\d+\.\d+ $today | save -f README.md

      - if: steps.update.outputs.UPDATED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatically update pre-commit hooks: ${{ steps.date.outputs.TODAY }}"
          tagging_message: ${{ steps.date.outputs.TODAY }}
